name: Elixir CI

on: push

jobs:
  ci:
    name: ci
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        include:
          - elixir: 1.10.x
            otp: 21.3.8.20
          - elixir: 1.11.x
            otp: 23.2.x
          - elixir: 1.12.x
            otp: 23.2.x
          - elixir: master
            otp: 23.2.x
    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
            ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles('**/mix.lock') }}
            ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix
    - name: Restore Dialyzer PLT cache
      uses: actions/cache@v2
      with:
        path: priv/plts
        key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-plt-${{ hashFiles('**/priv/plts/dialyzer.plt.hash') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-plt-${{ hashFiles('**/priv/plts/dialyzer.plt.hash') }}
          ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-plt
    - name: Install dependencies
      run: mix deps.get
    - name: mix check
      run: mix check
    - name: mix coveralls
      run: mix coveralls.github
      env:
        MIX_ENV: test
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}