name: Elixir CI

on: push

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: [1.10.3, 1.11.0, 1.12.1, 1.13.0-dev]
        otp: [22.3, 23.1, 24.0]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}
    - name: Install dependencies
      run: mix deps.get
    - name: mix check
      run: mix check