name: Elixir CI

on: push

jobs:
  ci:
    name: ci
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        elixir: [master]
        otp: [22.3, 23.1, 24.0]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}
    - name: Install dependencies
      run: mix deps.get
    - name: mix check
      run: mix check
    - name: mix coveralls
      run: mix coveralls.github